### ISSUE TITLE
No upper bounds for major versions of dependency

### ISSUE THREAD

**Issue by ulf1** [fzi-forschungszentrum-informatik/TSInterpret#14]
Example: What is going to happen when TensorFlow v3 comes out?
https://github.com/fzi-forschungszentrum-informatik/TSInterpret/blob/ce2025012d4bceb64fad298ad1dbd25aaf93bf5a/setup.py#L41

Use something like 
```
"tensorflow>=2.9.1,<3"
```

**Comment by JHoelli** [comment]
New PyPi Release (v.0.1.2). F
