### ISSUE TITLE
kaggle seems to be orphaned dependency

### ISSUE THREAD

**Issue by ulf1** [fzi-forschungszentrum-informatik/TSInterpret#16]
**Describe the bug**

the `kaggle` package isn't actually used in the python code, i.e. it's not needed for the installation process (e.g. setup.py).
https://github.com/search?q=repo%3Afzi-forschungszentrum-informatik%2FTSInterpret%20kaggle&type=code

if `kaggle` is only used as CLI downloader, then let end-users install it separately. Write a note the docs howto.

**To Reproduce**
Steps to reproduce the behavior. Also State the OS and the versions you are using.

**Additional context**

**Comment by JHoelli** [comment]
Thanks for the comment. This is resolved here : [https://github.com/fzi-forschungszentrum-informatik/TSInterpret/blob/main/setup.py](https://github.com/fzi-forschungszentrum-informatik/TSInterpret/blob/main/setup.py )and will be included in the next PyPI Release.

**Comment by JHoelli** [comment]
New PyPi Release (v.0.1.2).
