### ISSUE TITLE
How to contribute to the project as developer?

### ISSUE THREAD

**Issue by ulf1** [fzi-forschungszentrum-informatik/TSInterpret#19]
there is no call to action for developers in the README.md
- Should a developer create a Pull-Request (PR)?
- Should a developer just write issues?
- Does a developer keep his ownership of his code contribution? (see CLA processes, e.g., https://github.com/cla-assistant/cla-assistant or https://github.com/contributor-assistant/github-action)

**Comment by JHoelli** [comment]
Hi @ulf1,

The Basic Approach to Contributing can be found <a href="https://github.com/fzi-forschungszentrum-informatik/TSInterpret/blob/main/CONTRIBUTING.md"> here </a>. I also added a Link to the ReadMe.md. 

Thank for bringing our attention to the github CLA action, very useful. I added it to the main branch with Linux Developer Certificate Of Origin.

Best 
Jacqueline
