### ISSUE TITLE
[Q]Implements of TSEvo

### ISSUE THREAD

**Issue by HaoWenJohn** [fzi-forschungszentrum-informatik/TSInterpret#25]
It seems that in Evoutils.py line 100,should be 
`for item in items[0]:`
other than
`for item in items` ,because np.where return a tuple.
Uniform crossover operates on segmented timeseries,
not on whole feature.

**Comment by JHoelli** [comment]
Hi, 

thank you for opening the issue. Your feedbacks on TSInterpret are really helpful and valuable and really help to enhance our tool and resolve bugs.  :)  
 
Like for the your other issue, I fixed it and released a new version: https://pypi.org/project/TSInterpret/0.1.3/. I hope it works now. 

Feel free to open new issues with any other problem you you find or things you want to discuss. Like I said before, very helpful feedback. 

Best
