### ISSUE TITLE
[Q] Deprecation of Pandas forced (1.3.5)

### ISSUE THREAD

**Issue by hugo-rddi** [fzi-forschungszentrum-informatik/TSInterpret#32]
hi. 
I was trying to use this package for XAI purposes but there is a version management conflict. TSInterpret forces pandas to be  <= 1.3.5 when I want/need to use pandas2. 

Is there a way to have this with your package ?
Thanks a lot for your help

**Comment by JHoelli** [comment]
Hi 

which python version are you using? 
I will than try and replicate the issue and check for side effects.

**Comment by hugo-rddi** [comment]
Python 3.10

Our project is build upon multiple packages including pandas>=2.0 . Then we tried to install TSInterpret, it went well. 
However we perform Dataframe or Datarange operations as processing steps, that are no longer available because pandas has been downgraded back to 1.3.5

**Comment by JHoelli** [comment]
Hi,

I just soften the pandas restriction as it does not seem to have any side effects (at least according to the tests).
Feel free to test the new version by: 

```shell
pip install https://github.com/fzi-forschungszentrum-informatik/TSInterpret/archive/refs/heads/main.zip
```
Let me know if it works.

**Comment by hugo-rddi** [comment]
Seems to be working thanks !
