### ISSUE TITLE
Figsize argument not taken into account

### ISSUE THREAD

**Issue by hugo-rddi** [fzi-forschungszentrum-informatik/TSInterpret#41]
Hi again, 
Very minor issue but the  `exp.plot(..., figsize=())`  is not taken into account in your plot function. 

Code here : 
https://github.com/fzi-forschungszentrum-informatik/TSInterpret/blob/main/TSInterpret/InterpretabilityModels/FeatureAttribution.py#L190

Nothing that causes error or anything, but will be useful to have this hyperparameter working for dense and large time series for example. 
Thanks in advance !

**Comment by JHoelli** [comment]
Good Point. Thanks for bringing it to my attention.
Fixed with the new Release (v.0.3.4).
