### ISSUE TITLE
[Q]How can I explain the visualization of TSR on sample?

### ISSUE THREAD

**Issue by Ricky-zhang9678** [fzi-forschungszentrum-informatik/TSInterpret#42]
![image](https://github.com/fzi-forschungszentrum-informatik/TSInterpret/assets/84755128/b9868c13-63ec-4bfe-884a-e9b46c5b741e)
Dose this image illustrate the variation of feature importance over time？ If not, how can I find out the variation of feature importance over time?

Thanks!

**Comment by JHoelli** [comment]
Hi , 

what the visualization shows you, is that TSR (and the underlying feature attribution method) finds the values of Feature 0 between time steps 12 and 18 for the current example the most relevant for the predicted classification. So the most important time steps seem to be between 12 and 18 (in Feature 0). 

The generalization of TSR to identify the overall most important time steps (independent of the features ) - enabling conclusion like "the values between time step X and Y are the most important " and most important features (independent of the time steps) - "Feature 0 is overall the most important" - is currently not implemented in TSInterpret. (If you would find such a feature useful, it can be added. However, it would probably take a few weeks to be implemented.)

Does this help ? If not, a more detailed description of _variation of feature importance over time_ , maybe with an example or a conclusion you want to draw might help me to understand your needs.

**Comment by Ricky-zhang9678** [comment]
Yes! It's very helpful! Thanks a lot!
