### ISSUE TITLE
Trying to use COMTE and TSR but facing when plotting features #43

### ISSUE THREAD

**Issue by JanaSw** [fzi-forschungszentrum-informatik/TSInterpret#44]
Hello,

I am doing multivariate time series classification with 2 features.
When using the plot function with either COMTE or TSR only a portion of the features are being plotted for each instance.

When I debugged I suspected an issue with the reshape done in the plot.

BEFORE Reshape: In the below screenshot is the item values we can see 2 features starting both from 0 value:

![image](https://github.com/fzi-forschungszentrum-informatik/TSInterpret/assets/145288929/9886a7ea-324e-4f30-89ad-07089691f9cd)

AFTER Reshape: here we see that the reshape didn't conserve all the values of the feature (we can that not both features are starting at 0)

![image](https://github.com/fzi-forschungszentrum-informatik/TSInterpret/assets/145288929/d41274be-d1cc-4624-82cb-ccaa94c45938)

This is happening inside both plot functions: plot_in_one in CF.py at line 181 when it reshape the item
 and plot in Saliency_Base.py at line 61 when it reshape the item

Note: I am using tensorflow 

can you please help ? am I missing something or there is a bug ?

**Comment by JanaSw** [comment]
Hello @JHoelli 

Thank you for your reactivity !

Since you marked it as a bug do you any estimations when will you submit a fix?

**Comment by JHoelli** [comment]
Hi, 

I am currently fixing it. I hope to finish it in a few hours (afternnon / evening CEST ). (Checking for side effects unfortunately needs some time).

**Comment by JHoelli** [comment]
Hi,

you can install the patch with `https://github.com/fzi-forschungszentrum-informatik/TSInterpret/archive/refs/heads/swpaxes.zip` would be great if you could provide feedback, before I merge everything into the main branch. 

Thanks for reporting the issue.

**Comment by JHoelli** [comment]
Great, I just merged it in the Main Branch. 
The code will be available via PyPi with Release 0.4.4. (The release might take one or two more weeks.)
