### ISSUE TITLE
Small method name inconcistency

### ISSUE THREAD

**Issue by AlexisTabin** [fzi-forschungszentrum-informatik/TSInterpret#58]
Default method name is [NUN-CF](https://github.com/fzi-forschungszentrum-informatik/TSInterpret/blob/7437fbda535eb56c3e3998b913802d3b55951973/TSInterpret/InterpretabilityModels/counterfactual/NativeGuideCF.py#L44C1-L45C1).
Method name used for comparison in the explain method is [NUN_CF](https://github.com/fzi-forschungszentrum-informatik/TSInterpret/blob/7437fbda535eb56c3e3998b913802d3b55951973/TSInterpret/InterpretabilityModels/counterfactual/NativeGuideCF.py#L317C13-L317C14).

**Comment by JHoelli** [comment]
Hi @AlexisTabin,

Thanks for reporting the issue. 

It is now fixed and will be available with the new release 0.4.3.
