### ISSUE TITLE
Native Guide always generate counterfactual at the first

### ISSUE THREAD

**Issue by LbzSteven** [fzi-forschungszentrum-informatik/TSInterpret#63]
**Describe the bug**
When using the Native Guide method:
exp_model = NativeGuideCF(model, (train_x, train_y), backend='PYT', mode='feat', method='NUN_CF', max_iter=10000)

The generated results are always swapping components starting at the beginning of the datasets

ChinaTown:
![ChinaTown](https://github.com/fzi-forschungszentrum-informatik/TSInterpret/assets/43373047/271d8c07-7a2e-4f52-8bc2-e42733305231)

Coffee:
![coffee](https://github.com/fzi-forschungszentrum-informatik/TSInterpret/assets/43373047/6674dbb8-25dd-40f0-9772-9f1c0cbc75ae)

GunPoint:
![gunpoint](https://github.com/fzi-forschungszentrum-informatik/TSInterpret/assets/43373047/4d3e6bc3-b9b1-4999-b567-b2f809125c42)

**To Reproduce**
Steps to reproduce the behavior. Also State the OS and the versions you are using.

**Additional context**

**Comment by JHoelli** [comment]
Hi @LbzSteven,

thanks for reporting the issue. I solved it in the new release. 

Feel free to test it and reopen the issue if you still have problems.
