### ISSUE TITLE
SETS compatability for Pytorch

### ISSUE THREAD

**Issue by LbzSteven** [fzi-forschungszentrum-informatik/TSInterpret#68]
**Describe the bug**
For the pytorch model in SETS, there is an issue in set.py that model.predict doesn't work.

**To Reproduce**
Steps to reproduce the behavior. Also State the OS and the versions you are using.

**Additional context**

**Comment by JHoelli** [comment]
Hi, 

sorry for the delayed response, I was quite busy the past few months. I hope I was able to fix it now, but be aware that SETS  (in PyTorch) is still a bit buggy . I am tracking the known bugs in #54.
